### ISSUE TITLE
Unity.Netcode.Editor.CodeGen.NetworkBehaviourILPP: (0,0): error - System.NullReferenceException: Object reference not set to an instance of an object.| at

### ISSUE THREAD

**Issue by jzyong** [UnityTechnologies/GalacticKittens#11]
Unity.Netcode.Editor.CodeGen.NetworkBehaviourILPP: (0,0): error  - System.NullReferenceException: Object reference not set to an instance of an object.|   at Unity.Netcode.Editor.CodeGen.NetworkBehaviourILPP.GenerateVariableInitialization(TypeDefinition type)|   at Unity.Netcode.Editor.CodeGen.NetworkBehaviourILPP.GenerateVariableInitialization(TypeDefinition type)|   at Unity.Netcode.Editor.CodeGen.NetworkBehaviourILPP.ProcessNetworkBehaviour(TypeDefinition typeDefinition, String[] assemblyDefines)|   at System.Collections.Generic.List`1.ForEach(Action`1 action)|   at Unity.Netcode.Editor.CodeGen.NetworkBehaviourILPP.Process(ICompiledAssembly compiledAssembly)   at Unity.Netcode.Editor.CodeGen.NetworkBehaviourILPP.GenerateVariableInitialization(TypeDefinition type)|   at Unity.Netcode.Editor.CodeGen.NetworkBehaviourILPP.GenerateVariableInitialization(TypeDefinition type)|   at Unity.Netcode.Editor.CodeGen.NetworkBehaviourILPP.ProcessNetworkBehaviour(TypeDefinition typeDefinition, String[] assemblyDefines)|   at System.Collections.Generic.List`1.ForEach(Action`1 action)|   at Unity.Netcode.Editor.CodeGen.NetworkBehaviourILPP.Process(ICompiledAssembly compiledAssembly)

**Comment by DiogoCunha-Meta** [comment]
Any news about this?

**Comment by DiogoCunha-Meta** [comment]
I think I fixed it by updating the UnityNetCode package

**Comment by emgamedev-unity3d** [comment]
Hello,

I apologize for not replying sooner, but ATM I'm the only one maintaining this sample. This was an old error that was reported to the NGO team and fixed in ver. 1.5.2 of the SDK. So in the end you did the right call.
