### ISSUE TITLE
Example not working when trying to connect macOS <> iOS.

### ISSUE THREAD

**Issue by antiero** [UnityTechnologies/GalacticKittens#9]
Unity 2021.3.26f1, Xcode 14.3.1, macOS 13.4, iOS 16.5.

Is this example supposed to work on a local wireless network between different machines or only on the same local host?

I've successfully built, hosted and joined when building on the Mac, but when building, hosting/joining on iOS < Mac (or iOS <> iOS), it's not possible for a client to connect to the host.

The error on the iOS side is: [Netcode] Cannot start Client while an instance is already running, which seems related to #4

**Comment by emgamedev-unity3d** [comment]
Hello!

Thank you for checking out the sample! But unfortunately, ATM GK only works on PC/MAC and only local host. I have a development branch called [gk_with_relay](https://github.com/UnityTechnologies/GalacticKittens/tree/gk_with_relay), which does implement the [Relay](https://unity.com/products/relay) service, which lets you create P2P connections, but no mobile device input yet built-in.

**Comment by VKSharma17** [comment]
> Hello!
> 
> Thank you for checking out the sample! But unfortunately, ATM GK only works on PC/MAC and only local host. I have a development branch called [gk_with_relay](https://github.com/UnityTechnologies/GalacticKittens/tree/gk_with_relay), which does implement the [Relay](https://unity.com/products/relay) service, which lets you create P2P connections, but no mobile device input yet built-in.

The join code is not visible anywhere when running the build .exe. Join code only appears in the unity play mode console logs.
